CREATE TABLE Teams (
	ID INTEGER PRIMARY KEY NOT NULL,
	TEAM_NAME TEXT,
	RECORD TEXT,
	PLAYOFF_NOTES TEXT,
	ES1 INTEGER,
	ES2 INTEGER,
	ES3 INTEGER,
	ES4 INTEGER,
	ES5 INTEGER,
	PP1 INTEGER,
	PP2 INTEGER,
	PP3 INTEGER,
	PP4 INTEGER,
	PK1 INTEGER,
	PK2 INTEGER,
	PK3 INTEGER,
	PK4 INTEGER,
	FF1 INTEGER,
	FF2 INTEGER,
	FF3 INTEGER,
	TT1 INTEGER,
	TT2 INTEGER,
	TT3 INTEGER,
	SO INTEGER,
	EA INTEGER,
	G INTEGER,
	AHL_TEAM TEXT,
	AHL_RECORD TEXT,
	AHL_PLAYOFF_NOTES TEXT,
	AES1 INTEGER,
	AES2 INTEGER,
	AES3 INTEGER,
	AES4 INTEGER,
	AES5 INTEGER,
	AG INTEGER,
	FOREIGN KEY (ES1)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (ES2)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (ES3)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (ES4)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (ES5)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION
	FOREIGN KEY (PP1)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (PP2)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (PP3)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (PP4)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (PK1)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (PK2)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (PK3)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (PK4)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (FF1)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (FF2)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (FF3)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (TT1)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (TT2)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (TT3)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (SO)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (EA)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (G)
		REFERENCES Goalies (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (AES1)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (AES2)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (AES3)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (AES4)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION,
	FOREIGN KEY (AES5)
		REFERENCES Lines (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION
	FOREIGN KEY (AG)
		REFERENCES Goalies (ID)
			ON DELETE CASCADE
			ON UPDATE NO ACTION
);